name: PostUpgradeTask Angular

on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, reopened ]
    branches:
      - 'master'

jobs:
  postupgradetask:
    if: ${{ startsWith(github.head_ref, 'renovate/') && endsWith(github.head_ref, 'angular') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo github.head_ref
        run: echo ${{ github.head_ref }}

      - name: Parse branch name
        id: parse
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          echo "DEPNAME=$(echo $BRANCH | cut -d'/' -f2 | cut -d'-' -f3)" >> "$GITHUB_OUTPUT"
          echo "NEW_MAJOR=$(echo $BRANCH | cut -d'/' -f2 | cut -d'-' -f2)" >> "$GITHUB_OUTPUT"

      - name: echo parsed values
        env:
          DEPNAME: ${{ steps.parse.outputs.DEPNAME }}
          NEW_MAJOR: ${{ steps.parse.outputs.NEW_MAJOR }}
        run: echo "depname=${DEPNAME}, newMajor=${NEW_MAJOR}"

      - uses: actions/checkout@v3
        name: checkout
        with:
          ref: master

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Upgrade
        env:
          NEW_MAJOR: ${{ steps.parse.outputs.NEW_MAJOR }}
        run: |
          ls -al
          node -v
          npm -v
          npm install -g @angular/cli@^${NEW_MAJOR}
          npm ci
          ng update @angular/core@^${NEW_MAJOR} @angular/cli@^${NEW_MAJOR}
          ng update @angular/material@^${NEW_MAJOR} --allow-dirty

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.RENOVATE_TOKEN_ANGULAR }}
          title: Upgrade Angular to ${{ steps.parse.outputs.NEW_MAJOR }}
          branch: postupgradetask/${{ steps.parse.outputs.DEPNAME }}_${{ steps.parse.outputs.NEW_MAJOR }}
          base: master
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          body: |
            Upgrade Angular version
